# Generated by Django 4.2.7 on 2023-11-10 05:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoWatermarkingTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('schedule_time', models.DateTimeField(blank=True, null=True)),
                ('complete_time', models.DateTimeField(blank=True, null=True)),
                ('image_file', models.ImageField(upload_to='images/')),
                ('x_pos', models.DecimalField(decimal_places=11, max_digits=12)),
                ('y_pos', models.DecimalField(decimal_places=11, max_digits=12)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.video')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AudioExtractionTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('schedule_time', models.DateTimeField(blank=True, null=True)),
                ('complete_time', models.DateTimeField(blank=True, null=True)),
                ('audio_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.audio')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.video')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
