# Generated by Django 4.2.7 on 2023-11-10 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_alter_audio_file'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videowatermarkingtask',
            name='watermarked_video',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watermark_tasks', to='resources.video'),
        ),
    ]
