# Generated by Django 4.2.7 on 2023-11-10 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_videowatermarkingtask_watermarked_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='videowatermarkingtask',
            name='scale',
            field=models.DecimalField(blank=True, decimal_places=11, max_digits=12, null=True),
        ),
    ]
