# Generated by Django 4.2.7 on 2023-11-10 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_videowatermarkingtask_scale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videowatermarkingtask',
            name='scale',
            field=models.DecimalField(blank=True, decimal_places=11, max_digits=50, null=True),
        ),
        migrations.AlterField(
            model_name='videowatermarkingtask',
            name='x_pos',
            field=models.DecimalField(decimal_places=11, max_digits=20),
        ),
        migrations.AlterField(
            model_name='videowatermarkingtask',
            name='y_pos',
            field=models.DecimalField(decimal_places=11, max_digits=20),
        ),
    ]
