# Generated by Django 4.2.7 on 2023-11-10 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_videowatermarkingtask_scale_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videowatermarkingtask',
            name='scale',
            field=models.DecimalField(blank=True, decimal_places=40, max_digits=50, null=True),
        ),
        migrations.AlterField(
            model_name='videowatermarkingtask',
            name='x_pos',
            field=models.DecimalField(decimal_places=40, max_digits=50),
        ),
        migrations.AlterField(
            model_name='videowatermarkingtask',
            name='y_pos',
            field=models.DecimalField(decimal_places=40, max_digits=50),
        ),
    ]
