# Generated by Django 4.2.7 on 2023-11-11 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_alter_audio_file'),
        ('tasks', '0008_remove_audioextractiontask_celery_task_result_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audioextractiontask',
            name='audio_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resources.audio'),
        ),
    ]
